Package:
  FirstReply:
    - Готов проконсультировать вас по вопросам, связанным с пакетами услуг банка Уралсиб.
    - С удовольствием расскажу вам о пакетах услуг.
  SecondReply:
    - Уточните, какая операция вам требуется?
    - Выберите интересующую вас операцию.
  Buttons:
    - text: Оформить пакет услуг
      transition: /Premium/Premium
    - text: Тарифы и условия
      transition: /Package/Package/Terms
    - text: Оборот для условий бесплатности
      transition: /Package/Package/FreeTerms
    - text: Закрыть пакет услуг
      transition: /Package/Package/Close
      
Terms: |
    Получить информацию о тарифах на пакеты услуг можно:
    • В приложении «Уралсиб Онлайн» в разделе Главная -> Карты -> О карте -> Условия обслуживания. Или в [веб-версии на сайте](https://online.uralsib.ru): на главной странице выберите карту -> Информация -> Условия обслуживания
    • В чате «Уралсиб Онлайн»
    • По номеру горячей линии 8-800-250-57-57
    • На нашем сайте в разделе «Премиум» по [ссылке](https://www.uralsib.ru/premium)

TermsAnswer: Получить информацию по условиям и тарифам вашего пакета услуг можно по [ссылке]({{ $temp.PackageTermsLink }})

FreeTerms: |
    Информацию об обороте по карте для выполнения условия бесплатности пакета услуг вы можете получить:
    • В приложении «Уралсиб Онлайн» в разделе Главная -> Карты -> О карте
    • В [веб-версии на сайте](https://online.uralsib.ru), после выбора карты на главной странице
    • В чате «Уралсиб Онлайн»
    • По номеру горячей линии 8-800-250-57-57
    
Close: По вопросам закрытия пакета услуг переключаю вас на оператора.

GetPackagesError: Для получения информации по пакету услуг переключаю вас на оператора.

ChoosePackage:
    EmptyPackages:
        PackageTerms:
            AndroidOrIos: |
                Чтобы получить информацию о тарифах на пакеты услуг:
                1. В разделе «Главная» выберите карту.
                2. Далее в разделе «О карте» нажмите на кнопку «Условия обслуживания».
            Web: |
                Чтобы получить информацию о тарифах на пакеты услуг:
                1. На главной странице выберите карту.
                2. Далее в разделе «Информация» перейдите на вкладку «Условия обслуживания».
        PackageFreeTerms:
            AndroidOrIos: |
                Чтобы получить информацию об обороте по карте для выполнения условия бесплатности пакета услуг:
                1. В разделе «Главная» выберите карту. 
                2. Далее перейдите во вкладку «О карте».
            Web: Чтобы получить информацию об обороте по карте для выполнения условия бесплатности пакета услуг, на главной странице выберите нужную карту. 
    SomePackages: Выберите пакет услуг, по которому вам требуется информация.
    
GetPackageFreeTerms:
    - |
        {{ $session.name }}, для выполнения условия бесплатности по вашему пакету {{ $session.chosenPackage.name }} с основной картой {{ $session.chosenPackage.free.pan }} вами была потрачена сумма в размере {{ $temp.rubleForm1 }}.
    - Для выполнения условия необходимо было потратить {{ $temp.rubleForm2 }}. Условие бесплатности {{$session.chosenPackage.free.status}}.

GetPackageFreeTermsError: Для получения информации по обороту для условия бесплатности пакета услуг перевожу вас на оператора.

GetPackages:
  InactiveAPI:
    PackageTerms:
      AndroidOrIOS: |
        Чтобы получить информацию о тарифах на пакеты услуг:
        1. В разделе «Главная» выберите карту.
        2. Далее в разделе «О карте» нажмите на кнопку «Условия обслуживания».
      Web: |
        Чтобы получить информацию о тарифах на пакеты услуг:
        1. На главной странице выберите карту.
        2. Далее в разделе «Информация» перейдите на вкладку «Условия обслуживания».
    PackageFreeTerms:
      AndroidOrIOS: |
        Чтобы получить информацию об обороте по карте для выполнения условия бесплатности пакета услуг:
        1. В разделе «Главная» выберите карту. 
        2. Далее перейдите во вкладку «О карте».
      Web: Чтобы получить информацию об обороте по карте для выполнения условия бесплатности пакета услуг, на главной странице выберите нужную карту.  
    